# List, Dict to Series, DataFrame + List, Series, DataFrame to ndarray

## 目录

- list to series
- list to dataframe
- dict to series
- dict to dataframe

- list to ndarray
- series to ndarray
- dataframe to ndarray


## 输入 dict

- dict to series
- dict to dataframe

In [98]:
#coding:utf-8

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# dict
data = { 'state': ['Ohino', 'Ohino', 'Ohino', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002],
         'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}  # type(data) 为 dict

# dict to series，若不指定 index，data 的 key 充当 Series 的 index
ser = Series(data)

# dict to dataframe，若不指定 columns，data 的 key 充当 DataFrame 的 columns
df = DataFrame(data)

In [99]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohino', 'Ohino', 'Ohino', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [45]:
# dict to series，若不指定 index，data 的 key 充当 Series 的 index
ser = Series(data)
ser

pop                  [1.5, 1.7, 3.6, 2.4, 2.9]
state    [Ohino, Ohino, Ohino, Nevada, Nevada]
year            [2000, 2001, 2002, 2001, 2002]
dtype: object

In [46]:
ser.shape

(3,)

In [50]:
# dict to dataframe，若不指定 columns，data 的 key 充当 DataFrame 的 columns
df = DataFrame(data)
df

pop   state  year
0  1.5   Ohino  2000
1  1.7   Ohino  2001
2  3.6   Ohino  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

## 输入 List

- list to series
- list to dataframe
- list to ndarray
- series to ndarray
- dataframe to ndarray

In [103]:
#coding:utf-8

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# list
data = [[2000, 'Ohino', 1.5],
        [2001, 'Ohino', 1.7],
        [2002, 'Ohino', 3.6],
        [2001, 'Nevada', 2.4],
        [2002, 'Nevada, 2.9']]  # type(data) 为 list

# list to series
ser = Series(data, index = ['one', 'two', 'three', 'four', 'five'])

# list to dataframe
df = DataFrame(data, index = ['one', 'two', 'three', 'four', 'five'], columns = ['year', 'state', 'pop'])

# list to ndarray
ndarray = np.array(data)

# series to ndarray
foo = ser.as_matrix()
foo0 = Series.as_matrix(ser)

# dataframe to ndarray foo2 foo3 foo4 结果相同
foo1 = DataFrame.as_matrix(df)
foo2 = df.as_matrix()
foo3 = df.values
foo4 = np.array(df)

foo5 = df.as_matrix(["pop"])

In [17]:
type(data)

list

In [6]:
data

[[2000, 'Ohino', 1.5],
 [2001, 'Ohino', 1.7],
 [2002, 'Ohino', 3.6],
 [2001, 'Nevada', 2.4],
 [2002, 'Nevada, 2.9']]

In [7]:
# list to series
ser = Series(data, index = ['one', 'two', 'three', 'four', 'five'])
ser

one       [2000, Ohino, 1.5]
two       [2001, Ohino, 1.7]
three     [2002, Ohino, 3.6]
four     [2001, Nevada, 2.4]
five     [2002, Nevada, 2.9]
dtype: object

In [25]:
type(ser)

pandas.core.series.Series

In [26]:
ser.shape

(5,)

In [24]:
# list to dataframe
df = DataFrame(data, index = ['one', 'two', 'three', 'four', 'five'], columns = ['year', 'state', 'pop'])
df

year        state  pop
one    2000        Ohino  1.5
two    2001        Ohino  1.7
three  2002        Ohino  3.6
four   2001       Nevada  2.4
five   2002  Nevada, 2.9  NaN

In [27]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.shape

(5, 3)

In [15]:
type(df)

pandas.core.frame.DataFrame

In [104]:
# list to ndarray
ndarray = np.array(data)
ndarray

array([[2000, 'Ohino', 1.5], [2001, 'Ohino', 1.7], [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4], [2002, 'Nevada, 2.9']], dtype=object)

In [106]:
ndarray.shape

(5,)

In [ ]:
# series to ndarray
foo = ser.as_matrix()
foo0 = Series.as_matrix(ser)

In [55]:
foo

array([[2000, 'Ohino', 1.5], [2001, 'Ohino', 1.7], [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4], [2002, 'Nevada, 2.9']], dtype=object)

In [56]:
foo0

array([[2000, 'Ohino', 1.5], [2001, 'Ohino', 1.7], [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4], [2002, 'Nevada, 2.9']], dtype=object)

In [28]:
type(foo)

numpy.ndarray

In [57]:
foo.shape, foo0.shape

((5,), (5,))

In [ ]:
# dataframe to ndarray foo2 foo3 foo4 结果相同
foo1 = DataFrame.as_matrix(df)
foo2 = df.as_matrix()
foo3 = df.values
foo4 = np.array(df)

foo5 = df.as_matrix(["pop"])

In [52]:
foo1

array([[2000, 'Ohino', 1.5],
       [2001, 'Ohino', 1.7],
       [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4],
       [2002, 'Nevada, 2.9', nan]], dtype=object)

In [31]:
foo2

array([[2000, 'Ohino', 1.5],
       [2001, 'Ohino', 1.7],
       [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4],
       [2002, 'Nevada, 2.9', nan]], dtype=object)

In [34]:
foo3

array([[2000, 'Ohino', 1.5],
       [2001, 'Ohino', 1.7],
       [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4],
       [2002, 'Nevada, 2.9', nan]], dtype=object)

In [36]:
foo4

array([[2000, 'Ohino', 1.5],
       [2001, 'Ohino', 1.7],
       [2002, 'Ohino', 3.6],
       [2001, 'Nevada', 2.4],
       [2002, 'Nevada, 2.9', nan]], dtype=object)

In [39]:
foo5

array([[ 1.5],
       [ 1.7],
       [ 3.6],
       [ 2.4],
       [ nan]])

In [53]:
foo1.shape, foo2.shape, foo3.shape, foo4.shape, foo5.shape

((5, 3), (5, 3), (5, 3), (5, 3), (5, 1))

## 说明

本文整理自：[宁哥的小站](http://www.lining0806.com/numpy%E7%9A%84ndarray%E4%B8%8Epandas%E7%9A%84series%E5%92%8Cdataframe%E4%B9%8B%E9%97%B4%E4%BA%92%E8%BD%AC/)